-- Step 1: Create the cache table (run once)
CREATE TABLE IF NOT EXISTS `frido-429506.production.unified_orders_cache`
PARTITION BY order_date
CLUSTER BY Channel, Category
OPTIONS (require_partition_filter = false)
AS
WITH
sku_mapping AS (SELECT DISTINCT TRIM(productid) AS productid, TRIM(masterskucode) AS masterskucode FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__productid_sku_mapping` WHERE TRIM(masterskucode) NOT IN ('', 'not found')),
price_amazon AS (SELECT DISTINCT TRIM(productid) AS productid, SAFE_CAST(TRIM(REGEXP_REPLACE(Selling_Price, r'[^\x20-\x7E]', '')) AS FLOAT64) AS selling_price FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__productid_sku_mapping` WHERE TRIM(channelname) = 'Amazon'),
price_blinkit AS (SELECT DISTINCT TRIM(productid) AS productid, SAFE_CAST(TRIM(REGEXP_REPLACE(Selling_Price, r'[^\x20-\x7E]', '')) AS FLOAT64) AS selling_price FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__productid_sku_mapping` WHERE TRIM(channelname) = 'Blinkit'),
price_zepto AS (SELECT DISTINCT TRIM(productid) AS productid, SAFE_CAST(TRIM(REGEXP_REPLACE(Selling_Price, r'[^\x20-\x7E]', '')) AS FLOAT64) AS selling_price FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__productid_sku_mapping` WHERE TRIM(channelname) = 'Zepto'),
price_instamart AS (SELECT DISTINCT TRIM(productid) AS productid, SAFE_CAST(TRIM(REGEXP_REPLACE(Selling_Price, r'[^\x20-\x7E]', '')) AS FLOAT64) AS selling_price FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__productid_sku_mapping` WHERE TRIM(channelname) = 'Instamart'),
item_master AS (SELECT DISTINCT TRIM(Product_Code) AS Product_Code, TRIM(Category_Name) AS Category, TRIM(Sub_category) AS SubCategory, TRIM(GST_Tax_Type_Code) AS GST_Tax_Type_Code FROM `frido-429506.sharepoint_to_gcp.Frido_Item_Master__frido_item_sku_master` WHERE TRIM(Product_Code) != ''),
shopify_india AS (SELECT 'India' AS Country, order_name AS OrderId, 'Shopify' AS Channel, CASE WHEN source_name='Retail Store' THEN 'Retail Store' WHEN order_name LIKE '#MF%' THEN 'MyFrido' WHEN order_name LIKE '#FM%' THEN 'Mobility' ELSE source_name END AS SubChannel, CASE WHEN source_name='Retail Store' THEN 'Retail' WHEN order_name LIKE '#MF%' THEN 'MyFrido' WHEN order_name LIKE '#FM%' THEN 'Mobility' ELSE 'B2B' END AS ChannelAccount, order_date_ist AS OrderDate, shipping_state AS State, shipping_city AS City, shipping_pincode AS Pincode, sku AS ProductId, sku AS ChannelSKUCode, CAST(qty AS FLOAT64) AS ItemQty, CAST(final_total_incl_tax AS FLOAT64) AS SellingPrice_Inc_GST, CAST(selling_price_excl_shipping_tax AS FLOAT64) AS SellingPrice_Exc_GST, order_fulfillment_status AS FulfilmentStatus, financial_status AS FinancialStatus, CAST(item_gst_tax AS FLOAT64) AS Tax, CAST(is_refunded_line AS STRING) AS RefundStatus, gateway AS PaymentMode, customer_id AS CustomerId, voucher_code FROM `frido-429506.production.fact_shopify_myfrido_mobility_all_orders`),
shopify_b2b AS (SELECT 'India' AS Country, order_name AS OrderId, 'Shopify' AS Channel, 'Shopify B2B' AS SubChannel, 'Shopify B2B' AS ChannelAccount, order_date AS OrderDate, shipping_state AS State, shipping_city AS City, shipping_pincode AS Pincode, sku AS ProductId, sku AS ChannelSKUCode, CAST(qty AS FLOAT64) AS ItemQty, CAST(final_total_incl_tax AS FLOAT64) AS SellingPrice_Inc_GST, CAST(selling_price_excl_shipping_tax AS FLOAT64) AS SellingPrice_Exc_GST, line_fulfillment_status AS FulfilmentStatus, financial_status AS FinancialStatus, CAST(item_gst_tax AS FLOAT64) AS Tax, CAST(is_refunded_line AS STRING) AS RefundStatus, gateway AS PaymentMode, customer_id AS CustomerId, voucher_code FROM `frido-429506.production.fact_shopify_b2b_orders`),
shopify_international AS (SELECT 'International' AS Country, order_name AS OrderId, 'Shopify' AS Channel, CAST(NULL AS STRING) AS SubChannel, CASE WHEN currency='AED' THEN 'UAE' WHEN currency='GBP' THEN 'UK' WHEN currency='USD' THEN 'US' ELSE currency END AS ChannelAccount, order_date AS OrderDate, shipping_state AS State, shipping_city AS City, shipping_pincode AS Pincode, sku AS ProductId, sku AS ChannelSKUCode, CAST(qty AS FLOAT64) AS ItemQty, CAST(final_total_incl_tax AS FLOAT64) AS SellingPrice_Inc_GST, CAST(selling_price_excl_shipping_tax AS FLOAT64) AS SellingPrice_Exc_GST, order_fulfillment_status AS FulfilmentStatus, financial_status AS FinancialStatus, CAST(item_gst_tax AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, gateway AS PaymentMode, customer_id AS CustomerId, voucher_code FROM `frido-429506.production.fact_shopify_international_orders`),
amazon_seller_central AS (SELECT 'India' AS Country, amazon_order_id AS OrderId, 'Amazon' AS Channel, 'Amazon Seller Central' AS SubChannel, 'Seller Central' AS ChannelAccount, purchase_date_ist AS OrderDate, ship_state AS State, ship_city AS City, ship_postal_code AS Pincode, asin AS ProductId, sku AS ChannelSKUCode, CAST(quantity AS FLOAT64) AS ItemQty, CAST(item_price AS FLOAT64) AS SellingPrice_Inc_GST, CAST(NULL AS FLOAT64) AS SellingPrice_Exc_GST, item_status AS FulfilmentStatus, order_status AS FinancialStatus, CAST(item_tax AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, promotion_ids AS voucher_code FROM `frido-429506.production.amazon_seller_central_all_orders`),
amazon_vendor_central AS (SELECT 'India' AS Country, CONCAT('AVC', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY sales_date, asin) AS STRING), 6, '0')) AS OrderId, 'Amazon' AS Channel, 'Amazon Vendor Central' AS SubChannel, vendor_account AS ChannelAccount, sales_date AS OrderDate, CAST(NULL AS STRING) AS State, CAST(NULL AS STRING) AS City, CAST(NULL AS STRING) AS Pincode, asin AS ProductId, CAST(NULL AS STRING) AS ChannelSKUCode, CAST(orderedUnits AS FLOAT64) AS ItemQty, CAST(ordered_revenue AS FLOAT64) AS SellingPrice_Inc_GST, CAST(pa.selling_price AS FLOAT64) AS SellingPrice_Exc_GST, CAST(NULL AS STRING) AS FulfilmentStatus, CAST(NULL AS STRING) AS FinancialStatus, CAST(NULL AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.production.Amazon_Vendor_Central_sales_DateASIN_wise` LEFT JOIN price_amazon pa ON TRIM(asin) = pa.productid),
amazon_international AS (SELECT Country, amazon_order_id AS OrderId, 'Amazon' AS Channel, 'Amazon International' AS SubChannel, CASE WHEN UPPER(Country)='UK' THEN 'Amazon SC UK' WHEN UPPER(Country)='UAE' THEN 'Amazon SC UAE' ELSE Country END AS ChannelAccount, purchase_date_ist AS OrderDate, ship_state AS State, ship_city AS City, ship_postal_code AS Pincode, asin AS ProductId, sku AS ChannelSKUCode, CAST(quantity AS FLOAT64) AS ItemQty, CAST(item_price AS FLOAT64) AS SellingPrice_Inc_GST, CAST(NULL AS FLOAT64) AS SellingPrice_Exc_GST, item_status AS FulfilmentStatus, order_status AS FinancialStatus, CAST(item_tax AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, promotion_ids AS voucher_code FROM `frido-429506.production.amazon_seller_central_uk_uae_all_orders`),
flipkart AS (SELECT 'India' AS Country, order_id AS OrderId, 'Flipkart' AS Channel, CASE WHEN UPPER(TRIM(fulfilment_type))='FBF' THEN 'Flipkart FBF' ELSE 'Flipkart NON-FBF' END AS SubChannel, 'Flipkart' AS ChannelAccount, DATE(SUBSTR(order_date,1,10)) AS OrderDate, customer_s_delivery_state AS State, CAST(NULL AS STRING) AS City, customer_s_delivery_pincode AS Pincode, TRIM(REPLACE(fsn,'"','')) AS ProductId, TRIM(REPLACE(REGEXP_REPLACE(sku,r'"{2,}SKU:-*"{0,}',''),'"','')) AS ChannelSKUCode, CAST(item_quantity AS FLOAT64) AS ItemQty, CAST(price_after_discount_price_before_discount_total_discountx AS FLOAT64) AS SellingPrice_Inc_GST, CAST(taxable_value_final_invoice_amount_taxesx AS FLOAT64) AS SellingPrice_Exc_GST, event_sub_type AS FulfilmentStatus, order_type AS FinancialStatus, CAST(igst_amount AS FLOAT64) AS Tax, event_type AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.test_flipkart_dataset.sales_report`),
myntra AS (SELECT 'India' AS Country, store_order_id AS OrderId, 'Myntra' AS Channel, 'Myntra' AS SubChannel, 'Myntra' AS ChannelAccount, created_on AS OrderDate, state AS State, city AS City, zipcode AS Pincode, myntra_sku_code AS ProductId, seller_sku_code AS ChannelSKUCode, CAST(1 AS FLOAT64) AS ItemQty, CAST(final_amount AS FLOAT64) AS SellingPrice_Inc_GST, CAST(seller_price AS FLOAT64) AS SellingPrice_Exc_GST, order_status AS FulfilmentStatus, order_status AS FinancialStatus, CAST(tax_recovery AS FLOAT64) AS Tax, CAST(return_creation_date AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.production.fact_myntra_orders_report`),
cred AS (SELECT 'India' AS Country, DisplayOrderCode AS OrderId, 'CRED' AS Channel, 'CRED' AS SubChannel, ChannelName AS ChannelAccount, DATE(OrderDateasddmmyyyyhhMMss) AS OrderDate, ShippingAddressState AS State, ShippingAddressCity AS City, CAST(ShippingAddressPincode_in AS STRING) AS Pincode, ItemSKUCode AS ProductId, ItemSKUCode AS ChannelSKUCode, CAST(1 AS FLOAT64) AS ItemQty, CAST(COALESCE(NULLIF(TRIM(CAST(SellingPrice AS STRING)),''), NULLIF(TRIM(SellingPrice_st),''), '0') AS FLOAT64) AS SellingPrice_Inc_GST, CAST(Subtotal AS FLOAT64) AS SellingPrice_Exc_GST, ShippingPackageStatusCode AS FulfilmentStatus, SaleOrderStatus AS FinancialStatus, CAST(Tax AS FLOAT64) AS Tax, ReturnDate AS RefundStatus, PaymentInstrument AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, VoucherCode AS voucher_code FROM `frido-429506.production.Unicommerce_Sale_Orders_Report` WHERE LOWER(TRIM(ChannelName)) LIKE 'cred%' AND SaleOrderStatus != 'CANCELLED'),
firstcry AS (SELECT 'India' AS Country, DisplayOrderCode AS OrderId, 'Firstcry' AS Channel, 'Firstcry' AS SubChannel, ChannelName AS ChannelAccount, DATE(OrderDateasddmmyyyyhhMMss) AS OrderDate, ShippingAddressState AS State, ShippingAddressCity AS City, CAST(ShippingAddressPincode_in AS STRING) AS Pincode, ItemSKUCode AS ProductId, ItemSKUCode AS ChannelSKUCode, CAST(1 AS FLOAT64) AS ItemQty, CAST(COALESCE(NULLIF(TRIM(CAST(SellingPrice AS STRING)),''), NULLIF(TRIM(SellingPrice_st),''), '0') AS FLOAT64) AS SellingPrice_Inc_GST, CAST(Subtotal AS FLOAT64) AS SellingPrice_Exc_GST, ShippingPackageStatusCode AS FulfilmentStatus, SaleOrderStatus AS FinancialStatus, CAST(Tax AS FLOAT64) AS Tax, ReturnDate AS RefundStatus, PaymentInstrument AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, VoucherCode AS voucher_code FROM `frido-429506.production.Unicommerce_Sale_Orders_Report` WHERE LOWER(TRIM(ChannelName)) LIKE 'firstcry%' AND SaleOrderStatus != 'CANCELLED'),
pharmeasy AS (SELECT 'India' AS Country, DisplayOrderCode AS OrderId, 'Pharmeasy' AS Channel, 'Pharmeasy' AS SubChannel, ChannelName AS ChannelAccount, DATE(OrderDateasddmmyyyyhhMMss) AS OrderDate, ShippingAddressState AS State, ShippingAddressCity AS City, CAST(ShippingAddressPincode_in AS STRING) AS Pincode, ItemSKUCode AS ProductId, ItemSKUCode AS ChannelSKUCode, CAST(1 AS FLOAT64) AS ItemQty, CAST(COALESCE(NULLIF(TRIM(CAST(SellingPrice AS STRING)),''), NULLIF(TRIM(SellingPrice_st),''), '0') AS FLOAT64) AS SellingPrice_Inc_GST, CAST(Subtotal AS FLOAT64) AS SellingPrice_Exc_GST, ShippingPackageStatusCode AS FulfilmentStatus, SaleOrderStatus AS FinancialStatus, CAST(Tax AS FLOAT64) AS Tax, ReturnDate AS RefundStatus, PaymentInstrument AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, VoucherCode AS voucher_code FROM `frido-429506.production.Unicommerce_Sale_Orders_Report` WHERE LOWER(TRIM(ChannelName)) LIKE 'pharmeasy%' AND SaleOrderStatus != 'CANCELLED'),
blinkit AS (SELECT 'India' AS Country, CONCAT('BLI', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY date, item_id) AS STRING), 6, '0')) AS OrderId, 'Blinkit' AS Channel, 'Blinkit' AS SubChannel, 'Blinkit' AS ChannelAccount, date AS OrderDate, CAST(NULL AS STRING) AS State, city_name AS City, CAST(NULL AS STRING) AS Pincode, CAST(item_id AS STRING) AS ProductId, CAST(item_id AS STRING) AS ChannelSKUCode, CAST(qty_sold AS FLOAT64) AS ItemQty, CAST(mrp AS FLOAT64) AS SellingPrice_Inc_GST, CAST(pb.selling_price AS FLOAT64) AS SellingPrice_Exc_GST, CAST(NULL AS STRING) AS FulfilmentStatus, CAST(NULL AS STRING) AS FinancialStatus, CAST(NULL AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.production.fact_blinkit_sales_report` LEFT JOIN price_blinkit pb ON TRIM(CAST(item_id AS STRING)) = pb.productid),
zepto AS (SELECT 'India' AS Country, CONCAT('ZEP', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY date, sku_number) AS STRING), 6, '0')) AS OrderId, 'Zepto' AS Channel, 'Zepto' AS SubChannel, 'Zepto' AS ChannelAccount, date AS OrderDate, CAST(NULL AS STRING) AS State, city AS City, CAST(NULL AS STRING) AS Pincode, sku_number AS ProductId, sku_number AS ChannelSKUCode, CAST(sales_qty_units AS FLOAT64) AS ItemQty, CAST(gross_merchandise_value AS FLOAT64) AS SellingPrice_Inc_GST, CAST(pz.selling_price AS FLOAT64) AS SellingPrice_Exc_GST, CAST(NULL AS STRING) AS FulfilmentStatus, CAST(NULL AS STRING) AS FinancialStatus, CAST(NULL AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.production.zepto_sales_report` LEFT JOIN price_zepto pz ON TRIM(sku_number) = pz.productid),
instamart AS (SELECT 'India' AS Country, CONCAT('INS', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY ordered_date, item_code) AS STRING), 6, '0')) AS OrderId, 'Instamart' AS Channel, 'Instamart' AS SubChannel, 'Instamart' AS ChannelAccount, DATE(ordered_date) AS OrderDate, CAST(NULL AS STRING) AS State, city AS City, CAST(NULL AS STRING) AS Pincode, item_code AS ProductId, item_code AS ChannelSKUCode, CAST(units_sold AS FLOAT64) AS ItemQty, CAST(gmv AS FLOAT64) AS SellingPrice_Inc_GST, CAST(pi.selling_price AS FLOAT64) AS SellingPrice_Exc_GST, CAST(NULL AS STRING) AS FulfilmentStatus, CAST(NULL AS STRING) AS FinancialStatus, CAST(NULL AS FLOAT64) AS Tax, CAST(NULL AS STRING) AS RefundStatus, CAST(NULL AS STRING) AS PaymentMode, CAST(NULL AS STRING) AS CustomerId, CAST(NULL AS STRING) AS voucher_code FROM `frido-429506.production.fact_instamart_sales_report` LEFT JOIN price_instamart pi ON TRIM(item_code) = pi.productid),
unicommerce_status_map AS (SELECT TRIM(DisplayOrderCode) AS order_id, CASE WHEN UPPER(ShippingPackageStatusCode)='DELIVERED' THEN ShippingPackageStatusCode WHEN UPPER(ShippingPackageStatusCode) IN ('RETURNED','RETURN_EXPECTED','RETURN_ACKNOWLEDGED') THEN ShippingPackageStatusCode WHEN UPPER(SaleOrderItemStatus)='CANCELLED' THEN SaleOrderItemStatus WHEN UPPER(SaleOrderItemStatus)='DISPATCHED' THEN SaleOrderItemStatus ELSE NULL END AS unicommerce_status, COALESCE(CAST(DeliveryTime_dtm AS STRING), CAST(DeliveryTime AS STRING)) AS delivered_date_uni, COALESCE(CAST(DispatchDate_dtm AS STRING), CAST(DispatchDate AS STRING)) AS dispatch_date_uni FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY DisplayOrderCode ORDER BY Updated DESC) AS rn FROM `frido-429506.production.Unicommerce_Sale_Orders_Report` WHERE DisplayOrderCode IS NOT NULL) WHERE rn = 1),
clickpost_status_map AS (SELECT TRIM(order_id) AS order_id, clickpost_unified_status, delivery_date, out_for_pickup_1st_attempt FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC) AS rn FROM `frido-429506.production.Clickpost_Shipment_Tracking_Report` WHERE order_id IS NOT NULL AND LOWER(TRIM(shipment_type))='forward') WHERE rn = 1),
cancelled_orders AS (SELECT TRIM(DisplayOrderCode) AS order_id, 1 AS is_cancelled FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY DisplayOrderCode ORDER BY Updated DESC) AS rn FROM `frido-429506.production.Unicommerce_Sale_Orders_Report` WHERE DisplayOrderCode IS NOT NULL AND SaleOrderItemStatus='CANCELLED') WHERE rn = 1),
rto_shipments AS (SELECT TRIM(order_id) AS order_id, 1 AS is_rto FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY updated_at DESC) AS rn FROM `frido-429506.production.Clickpost_Shipment_Tracking_Report` WHERE order_id IS NOT NULL AND (UPPER(clickpost_unified_status) LIKE 'RTO%' OR rto_mark_date IS NOT NULL)) WHERE rn = 1),
cir_returns AS (SELECT TRIM(forward_order_id) AS order_id, 1 AS is_cir_return, CASE WHEN UPPER(TRIM(Return_Type))='EXCHANGE' THEN 1 ELSE 0 END AS is_exchange FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY forward_order_id ORDER BY request_created_on DESC) AS rn FROM `frido-429506.production.Clickpost_Returns_Exchange_Report` WHERE forward_order_id IS NOT NULL) WHERE rn = 1),
unified AS (SELECT * FROM shopify_india UNION ALL SELECT * FROM shopify_b2b UNION ALL SELECT * FROM shopify_international UNION ALL SELECT * FROM amazon_seller_central UNION ALL SELECT * FROM amazon_vendor_central UNION ALL SELECT * FROM amazon_international UNION ALL SELECT * FROM flipkart UNION ALL SELECT * FROM myntra UNION ALL SELECT * FROM cred UNION ALL SELECT * FROM firstcry UNION ALL SELECT * FROM pharmeasy UNION ALL SELECT * FROM blinkit UNION ALL SELECT * FROM zepto UNION ALL SELECT * FROM instamart)
SELECT
  u.OrderDate AS order_date,
  u.OrderId AS order_id,
  u.Channel AS channel,
  u.SubChannel AS sub_channel,
  u.ChannelAccount AS channel_account,
  u.Country AS country,
  u.State AS state,
  u.City AS city,
  u.Pincode AS pincode,
  u.ProductId AS product_id,
  u.ChannelSKUCode AS sku_code,
  COALESCE(sm.masterskucode, TRIM(u.ProductId)) AS master_sku,
  COALESCE(im.Category, 'Frido') AS category,
  COALESCE(im.SubCategory, 'Frido') AS sub_category,
  u.ItemQty AS item_qty,
  u.SellingPrice_Inc_GST AS revenue_inc_gst,
  CASE WHEN SAFE_CAST(im.GST_Tax_Type_Code AS FLOAT64) IS NOT NULL THEN u.SellingPrice_Inc_GST / (1 + SAFE_CAST(im.GST_Tax_Type_Code AS FLOAT64) / 100) WHEN u.SellingPrice_Exc_GST IS NOT NULL AND u.SellingPrice_Exc_GST != 0 THEN u.SellingPrice_Exc_GST ELSE u.SellingPrice_Inc_GST / 1.18 END AS revenue_exc_gst,
  u.PaymentMode AS payment_mode,
  u.CustomerId AS customer_id,
  u.voucher_code AS voucher_code,
  u.FulfilmentStatus AS fulfilment_status,
  u.FinancialStatus AS financial_status,
  CASE WHEN UPPER(us.unicommerce_status)='DELIVERED' THEN 'Delivered' WHEN UPPER(cs.clickpost_unified_status) LIKE '%DELIVERED%' THEN 'Delivered' WHEN UPPER(us.unicommerce_status)='CANCELLED' THEN 'Cancelled' WHEN UPPER(cs.clickpost_unified_status) LIKE '%CANCELLED%' THEN 'Cancelled' WHEN UPPER(cs.clickpost_unified_status) LIKE 'RTO%' THEN 'RTO' WHEN UPPER(us.unicommerce_status) IN ('RETURNED','RETURN_EXPECTED','RETURN_ACKNOWLEDGED') THEN 'RTO' WHEN UPPER(us.unicommerce_status)='DISPATCHED' THEN 'Dispatched' WHEN UPPER(cs.clickpost_unified_status) LIKE '%DISPATCHED%' THEN 'Dispatched' ELSE NULL END AS order_status,
  CASE WHEN u.Channel='Shopify' THEN COALESCE(rto.is_rto, 0) ELSE NULL END AS is_rto,
  CASE WHEN u.Channel='Shopify' THEN COALESCE(co.is_cancelled, 0) ELSE NULL END AS is_cancelled,
  CASE WHEN u.Channel='Shopify' THEN COALESCE(cr.is_cir_return, 0) ELSE NULL END AS is_cir_return,
  CASE WHEN u.Channel='Shopify' THEN COALESCE(cr.is_exchange, 0) ELSE NULL END AS is_exchange,
  COALESCE(CAST(us.dispatch_date_uni AS STRING), CAST(cs.out_for_pickup_1st_attempt AS STRING)) AS dispatch_date,
  COALESCE(CAST(us.delivered_date_uni AS STRING), CAST(cs.delivery_date AS STRING)) AS delivered_date
FROM unified u
LEFT JOIN sku_mapping sm ON TRIM(u.ProductId) = sm.productid
LEFT JOIN item_master im ON COALESCE(sm.masterskucode, TRIM(u.ProductId)) = im.Product_Code
LEFT JOIN cir_returns cr ON TRIM(u.OrderId) = cr.order_id
LEFT JOIN rto_shipments rto ON TRIM(u.OrderId) = rto.order_id
LEFT JOIN cancelled_orders co ON TRIM(u.OrderId) = co.order_id
LEFT JOIN unicommerce_status_map us ON TRIM(u.OrderId) = us.order_id
LEFT JOIN clickpost_status_map cs ON TRIM(u.OrderId) = cs.order_id
